apiVersion: apps/v1
kind: Deployment
metadata:
  name: gapstack-website-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gapstack-website-backend
  template:
    metadata:
      labels:
        app: gapstack-website-backend
    spec:
      containers:
        - name: gapstack-website-backend
          image: gastaging.azurecr.io/website-backend:v3
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: gapstack-website-backend
spec:
  selector:
    app: gapstack-website-backend
  ports:
    - port: 100
      targetPort: 4000
  type: LoadBalancer